---
- name: Adding webadmin user
  user: name=webadmin shell=/bin/bash groups=www-data

- name: Ensure directories are 0755
  command: find {{ drupal_base }} -type d -exec chmod 0755 {} \;

- name: Ensure files are 0644
  command: find {{ drupal_base }} -type f -exec chmod 0644 {} \;

- name: Correct Drupal installation owner
  file: dest={{ drupal_base }}
         owner=webadmin group=webadmin
         recurse=yes
  sudo: yes

- name: Set Drupal public files permissions
  file: dest={{ drupal_base }}/sites/default/files
         owner=www-data group=www-data
         recurse=yes
  sudo: yes

- name: Setting stickybit sites/default/files permissions
  command: chmod g+s {{ drupal_base }}/sites/default/files
  sudo: yes

- name: Running drush pm-update
  shell: /usr/bin/drush pm-update -y chdir={{ drupal_base }}
  su: yes
  su_user: webadmin
  